# Generated by GitHub Copilot

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=30)),
                ("nombre", models.CharField(max_length=50)),
                (
                    "rol",
                    models.CharField(
                        choices=[("ADMIN", "ADMIN"), ("PLAYER", "PLAYER")],
                        default="PLAYER",
                        max_length=6,
                    ),
                ),
            ],
        ),
    ]
