# Generated by GitHub Copilot

from django.conf import settings
from django.db import migrations


TEST_USERS = [
    {
        "username": "admin",
        "password": "admin1234",
        "is_staff": True,
        "is_superuser": True,
    },
    {
        "username": "player",
        "password": "player1234",
        "is_staff": False,
        "is_superuser": False,
    },
]


def _get_user_model(apps):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    return apps.get_model(app_label, model_name)


def seed_test_users(apps, schema_editor):
    UserModel = _get_user_model(apps)

    for user_spec in TEST_USERS:
        username = user_spec["username"]
        password = user_spec["password"]

        user, _created = UserModel.objects.get_or_create(username=username)
        user.is_staff = user_spec["is_staff"]
        user.is_superuser = user_spec["is_superuser"]

        user.save()


def unseed_test_users(apps, schema_editor):
    UserModel = _get_user_model(apps)
    usernames = [u["username"] for u in TEST_USERS]
    UserModel.objects.filter(username__in=usernames).delete()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_test_users, reverse_code=unseed_test_users),
    ]
