# Generated by GitHub Copilot

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations


TEST_USERS = [
    {
        "username": "admin",
        "password": "admin1234",
        "is_staff": True,
        "is_superuser": True,
        "nombre": "El Admin",
        "email": "admin@example.com",
    },
    {
        "username": "player",
        "password": "player1234",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "El Jugador",
        "email": "player@example.com",
    },
    {
        "username": "user01",
        "password": "user1234",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 01",
        "email": "user01@example.com",
    },
    {
        "username": "user02",
        "password": "user1234",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 02",
        "email": "user02@example.com",
    },
    {
        "username": "user03",
        "password": "user1234",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 03",
        "email": "user03@example.com",
    },
    {
        "username": "user04",
        "password": "user1234",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 04",
        "email": "user04@example.com",
    },
    {
        "username": "user05",
        "password": "user1234",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 05",
        "email": "user05@example.com",
    },
    {
        "username": "user06",
        "password": "user1234",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 06",
        "email": "user06@example.com",
    },
    {
        "username": "user07",
        "password": "user1234",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 07",
        "email": "user07@example.com",
    },
    {
        "username": "user08",
        "password": "user1234",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 08",
        "email": "user08@example.com",
    },
    {
        "username": "user09",
        "password": "user1234",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 09",
        "email": "user09@example.com",
    },
    {
        "username": "user10",
        "password": "user1234",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 10",
        "email": "user10@example.com",
    },
]


def _get_user_model(apps):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    return apps.get_model(app_label, model_name)


def seed_test_users(apps, schema_editor):
    UserModel = _get_user_model(apps)

    for user_spec in TEST_USERS:
        username = user_spec["username"]
        password = user_spec["password"]

        defaults = {
            "password": make_password(password),
            "is_staff": user_spec["is_staff"],
            "is_superuser": user_spec["is_superuser"],
            "is_active": True,
            "email": user_spec.get("email", ""),
            "nombre": user_spec["nombre"],
            "puntuacion": 0,
            "imagen": user_spec.get("imagen", ""),
        }

        UserModel.objects.update_or_create(username=username, defaults=defaults)


def unseed_test_users(apps, schema_editor):
    UserModel = _get_user_model(apps)
    usernames = [u["username"] for u in TEST_USERS]
    UserModel.objects.filter(username__in=usernames).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_test_users, reverse_code=unseed_test_users),
    ]
