# Generated by GitHub Copilot

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations


TEST_USERS = [
    {
        "username": "breen",
        "password": "123456",
        "is_staff": True,
        "is_superuser": True,
        "nombre": "Dr. Breen",
        "email": "admin@matacartas.es",
        "puntuacion": 1000,
    },
    {
        "username": "lukash",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Lukash",
        "email": "lukash@freedom.ukr",
        "puntuacion": 500,
    },
    {
        "username": "user01",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 01",
        "email": "user01@example.com",
        "puntuacion": 100,
    },
    {
        "username": "user02",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 02",
        "email": "user02@example.com",
        "puntuacion": 150,
    },
    {
        "username": "user03",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 03",
        "email": "user03@example.com",
        "puntuacion": 200,
    },
    {
        "username": "user04",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 04",
        "email": "user04@example.com",
        "puntuacion": 250,
    },
    {
        "username": "user05",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 05",
        "email": "user05@example.com",
        "puntuacion": 300,
    },
    {
        "username": "user06",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 06",
        "email": "user06@example.com",
        "puntuacion": 350,
    },
    {
        "username": "user07",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 07",
        "email": "user07@example.com",
        "puntuacion": 400,
    },
    {
        "username": "user08",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 08",
        "email": "user08@example.com",
        "puntuacion": 500,
    },
    {
        "username": "user09",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario 09",
        "email": "user09@example.com",
        "puntuacion": 600,
    },
    {
        "username": "freeman",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Dr. Freeman",
        "email": "freeman@blackmesa.us",
        "puntuacion": 700,
    },
]

RANGO_SEED = [
    {
        "nombre": "Novato",
        "color": "gris",
        "puntos_minimos": 50,
        "puntos_maximos": 100,
    },
    {
        "nombre": "Experimentado",
        "color": "verde",
        "puntos_minimos": 101,
        "puntos_maximos": 300,
    },
    {
        "nombre": "Veterano",
        "color": "rojo",
        "puntos_minimos": 301,
        "puntos_maximos": 500,
    },
    {
        "nombre": "Maestro",
        "color": "morado",
        "puntos_minimos": 501,
        "puntos_maximos": 700,
    },
    {
        "nombre": "Gran capitan",
        "color": "amarillo_dorado",
        "puntos_minimos": 701,
        "puntos_maximos": 1500,
    },
]


def _get_user_model(apps):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    return apps.get_model(app_label, model_name)


def seed_test_users(apps, schema_editor):
    UserModel = _get_user_model(apps)

    for user_spec in TEST_USERS:
        username = user_spec["username"]
        password = user_spec["password"]

        defaults = {
            "password": make_password(password),
            "is_staff": user_spec["is_staff"],
            "is_superuser": user_spec["is_superuser"],
            "is_active": True,
            "email": user_spec.get("email", ""),
            "nombre": user_spec["nombre"],
            "puntuacion": user_spec.get("puntuacion", 0),
            "imagen": user_spec.get("imagen", ""),
        }

        UserModel.objects.update_or_create(username=username, defaults=defaults)


def seed_rangos(apps, schema_editor):
    Rango = apps.get_model("api", "Rango")
    for rango in RANGO_SEED:
        Rango.objects.update_or_create(nombre=rango["nombre"], defaults=rango)


def unseed_test_users(apps, schema_editor):
    UserModel = _get_user_model(apps)
    usernames = [u["username"] for u in TEST_USERS]
    UserModel.objects.filter(username__in=usernames).delete()


def unseed_rangos(apps, schema_editor):
    Rango = apps.get_model("api", "Rango")
    nombres = [rango["nombre"] for rango in RANGO_SEED]
    Rango.objects.filter(nombre__in=nombres).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_test_users, reverse_code=unseed_test_users),
        migrations.RunPython(seed_rangos, reverse_code=unseed_rangos),
    ]
