CATALOGO = {

    ##############################################################################################################
    # CARTAS NORMALES 
    ##############################################################################################################

    # OROS
    "2_OROS": {
        "fuerza": 1,
        "riqueza": 111,
        "tipo": "normal",
        "posicion": "02oro",
    },
    "3_OROS": {
        "fuerza": 2,
        "riqueza": 112,
        "tipo": "normal",
        "posicion": "03oro",
    },
    "4_OROS": {
        "fuerza": 3,
        "riqueza": 113,
        "tipo": "normal",
        "posicion": "04oro",
    },
    "5_OROS": {
        "fuerza": 4,
        "riqueza": 114,
        "tipo": "normal",
        "posicion": "05oro",
    },
    "6_OROS": {
        "fuerza": 5,
        "riqueza": 115,
        "tipo": "normal",
        "posicion": "06oro",
    },
    "7_OROS": {
        "fuerza": 6,
        "riqueza": 116,
        "tipo": "normal",
        "posicion": "07oro",
    },
    "8_OROS": {
        "fuerza": 7,
        "riqueza": 117,
        "tipo": "normal",
        "posicion": "08oro",
    },
    "9_OROS": {
        "fuerza": 8,
        "riqueza": 118,
        "tipo": "normal",
        "posicion": "09oro",
    },
    "10_OROS": {
        "fuerza": 9,
        "riqueza": 119,
        "tipo": "normal",
        "posicion": "10oro",
    },
    "11_OROS": {
        "fuerza": 10,
        "riqueza": 120,
        "tipo": "normal",
        "posicion": "11oro",
    },
    "12_OROS": {
        "fuerza": 11,
        "riqueza": 121,
        "tipo": "normal",
        "posicion": "12oro",
    },
    "1_OROS": {
        "fuerza": 12,
        "riqueza": 129,
        "tipo": "normal",
        "posicion": "01oro",
    },

    # COPAS
    "2_COPAS": {
        "fuerza": 21,
        "riqueza": 91,
        "tipo": "normal",
        "posicion": "02cop",
    },
    "3_COPAS": {
        "fuerza": 22,
        "riqueza": 92,
        "tipo": "normal",
        "posicion": "03cop",
    },
    "4_COPAS": {
        "fuerza": 23,
        "riqueza": 93,
        "tipo": "normal",
        "posicion": "04cop",
    },
    "5_COPAS": {
        "fuerza": 24,
        "riqueza": 94,
        "tipo": "normal",
        "posicion": "05cop",
    },
    "6_COPAS": {
        "fuerza": 25,
        "riqueza": 95,
        "tipo": "normal",
        "posicion": "06cop",
    },
    "7_COPAS": {
        "fuerza": 26,
        "riqueza": 96,
        "tipo": "normal",
        "posicion": "07cop",
    },
    "8_COPAS": {
        "fuerza": 27,
        "riqueza": 97,
        "tipo": "normal",
        "posicion": "08cop",
    },
    "9_COPAS": {
        "fuerza": 28,
        "riqueza": 98,
        "tipo": "normal",
        "posicion": "09cop",
    },
    "10_COPAS": {
        "fuerza": 29,
        "riqueza": 99,
        "tipo": "normal",
        "posicion": "10cop",
    },
    "11_COPAS": {
        "fuerza": 30,
        "riqueza": 100,
        "tipo": "normal",
        "posicion": "11cop",
    },
    "12_COPAS": {
        "fuerza": 31,
        "riqueza": 101,
        "tipo": "normal",
        "posicion": "12cop",
    },
    "1_COPAS": {
        "fuerza": 32,
        "riqueza": 102,
        "tipo": "normal",
        "posicion": "01cop",
        "matadoras": ("2_OROS",),
        "recompensa": 3,
    },

    # BASTOS
    "2_BASTOS": {
        "fuerza": 51,
        "riqueza": 51,
        "tipo": "normal",
        "posicion": "02bas",
        "matadoras": ("10_COPAS","11_COPAS","12_COPAS","1_COPAS",),
        "recompensa": 1,
    },
    "3_BASTOS": {
        "fuerza": 52,
        "riqueza": 52,
        "tipo": "normal",
        "posicion": "03bas",
        "matadoras": ("10_COPAS","11_COPAS","12_COPAS","1_COPAS",),
        "recompensa": 1,
    },
    "4_BASTOS": {
        "fuerza": 53,
        "riqueza": 53,
        "tipo": "normal",
        "posicion": "04bas",
        "matadoras": ("10_COPAS","11_COPAS","12_COPAS","1_COPAS",),
        "recompensa": 1,
    },
    "5_BASTOS": {
        "fuerza": 54,
        "riqueza": 54,
        "tipo": "normal",
        "posicion": "05bas",
        "matadoras": ("10_COPAS","11_COPAS","12_COPAS","1_COPAS",),
        "recompensa": 1,
    },
    "6_BASTOS": {
        "fuerza": 55,
        "riqueza": 55,
        "tipo": "normal",
        "posicion": "06bas",
        "matadoras": ("10_COPAS","11_COPAS","12_COPAS","1_COPAS",),
        "recompensa": 1,
    },
    "7_BASTOS": {
        "fuerza": 56,
        "riqueza": 56,
        "tipo": "normal",
        "posicion": "07bas",
        "matadoras": ("10_COPAS","11_COPAS","12_COPAS","1_COPAS",),
        "recompensa": 1,
    },
    "8_BASTOS": {
        "fuerza": 57,
        "riqueza": 57,
        "tipo": "normal",
        "posicion": "08bas",
        "matadoras": ("10_COPAS","11_COPAS","12_COPAS","1_COPAS",),
        "recompensa": 1,
    },
    "9_BASTOS": {
        "fuerza": 58,
        "riqueza": 58,
        "tipo": "normal",
        "posicion": "09bas",
        "matadoras": ("10_COPAS","11_COPAS","12_COPAS","1_COPAS",),
        "recompensa": 1,
    },
    "10_BASTOS": {
        "fuerza": 59,
        "riqueza": 59,
        "tipo": "normal",
        "posicion": "10bas",
        "matadoras": ("4_OROS","5_OROS","4_COPAS","5_COPAS",),
        "recompensa": 2,
    },
    "11_BASTOS": {
        "fuerza": 60,
        "riqueza": 60,
        "tipo": "normal",
        "posicion": "11bas",
        "matadoras": ("4_OROS","5_OROS","4_COPAS","5_COPAS",),
        "recompensa": 2,
    },
    "12_BASTOS": {
        "fuerza": 61,
        "riqueza": 61,
        "tipo": "normal",
        "posicion": "12bas",
        "matadoras": ("4_COPAS","5_COPAS","4_OROS","5_OROS",),
        "recompensa": 2,
    },
    "1_BASTOS": {
        "fuerza": 62,
        "riqueza": 62,
        "tipo": "normal",
        "posicion": "01bas",
        "matadoras": ("2_OROS","3_OROS","2_COPAS","3_COPAS",),
        "recompensa": 3,
    },

    # ESPADAS
    "2_ESPADAS": {
        "fuerza": 71,
        "riqueza": 41,
        "tipo": "normal",
        "posicion": "02esp",
        "matadoras": ("5_COPAS","6_COPAS","7_COPAS","8_COPAS","9_COPAS"),
        "recompensa": 1,
    },
    "3_ESPADAS": {
        "fuerza": 72,
        "riqueza": 42,
        "tipo": "normal",
        "posicion": "03esp",
        "matadoras": ("5_COPAS","6_COPAS","7_COPAS","8_COPAS","9_COPAS"),
        "recompensa": 1,
    },
    "4_ESPADAS": {
        "fuerza": 73,
        "riqueza": 43,
        "tipo": "normal",
        "posicion": "04esp",
        "matadoras": ("5_COPAS","6_COPAS","7_COPAS","8_COPAS","9_COPAS",),
        "recompensa": 1,
    },
    "5_ESPADAS": {
        "fuerza": 74,
        "riqueza": 44,
        "tipo": "normal",
        "posicion": "05esp",
        "matadoras": ("5_COPAS","6_COPAS","7_COPAS","8_COPAS","9_COPAS",),
        "recompensa": 1,
    },
    "6_ESPADAS": {
        "fuerza": 75,
        "riqueza": 45,
        "tipo": "normal",
        "posicion": "06esp",
        "matadoras": ("5_COPAS","6_COPAS","7_COPAS","8_COPAS","9_COPAS",),
        "recompensa": 1,
    },
    "7_ESPADAS": {
        "fuerza": 76,
        "riqueza": 46,
        "tipo": "normal",
        "posicion": "07esp",
        "matadoras": ("5_COPAS","6_COPAS","7_COPAS","8_COPAS","9_COPAS",),
        "recompensa": 1,
    },
    "8_ESPADAS": {
        "fuerza": 77,
        "riqueza": 47,
        "tipo": "normal",
        "posicion": "08esp",
        "matadoras": ("5_COPAS","6_COPAS","7_COPAS","8_COPAS","9_COPAS",),
        "recompensa": 1,
    },
    "9_ESPADAS": {
        "fuerza": 78,
        "riqueza": 48,
        "tipo": "normal",
        "posicion": "09esp",
        "matadoras": ("5_COPAS","6_COPAS","7_COPAS","8_COPAS","9_COPAS",),
        "recompensa": 1,
    },
    "10_ESPADAS": {
        "fuerza": 79,
        "riqueza": 49,
        "tipo": "normal",
        "posicion": "10esp",
        "matadoras": ("6_OROS","7_OROS","8_OROS","9_OROS",),
        "recompensa": 2,
    },
    "11_ESPADAS": {
        "fuerza": 80,
        "riqueza": 50,
        "tipo": "normal",
        "posicion": "11esp",
        "matadoras": ("6_OROS","7_OROS","8_OROS","9_OROS",),
        "recompensa": 2,
    },
    "12_ESPADAS": {
        "fuerza": 81,
        "riqueza": 51,
        "tipo": "normal",
        "posicion": "12esp",
        "matadoras": ("6_OROS","7_OROS","8_OROS","9_OROS",),
        "recompensa": 2,
    },
    "1_ESPADAS": {
        "fuerza": 82,
        "riqueza": 52,
        "tipo": "normal",
        "posicion": "01esp",
        "matadoras": ("6_BASTOS","7_BASTOS","8_BASTOS","9_BASTOS",),
        "recompensa": 3,
    },

    ##############################################################################################################
    # CARTAS ESPECIALES 
    ##############################################################################################################
    
    # CARTAS VALIOSAS

    "3_JOYAS_REALES": {
        "fuerza": 33,
        "riqueza": 122,
        "tipo": "especial_val",
        "posicion": "03oro",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "4_JOYAS_REALES": {
        "fuerza": 34,
        "riqueza": 123,
        "tipo": "especial_val",
        "posicion": "04oro",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "5_JOYAS_REALES": {
        "fuerza": 35,
        "riqueza": 124,
        "tipo": "especial_val",
        "posicion": "05oro",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "6_JOYAS_REALES": {
        "fuerza": 36,
        "riqueza": 125,
        "tipo": "especial_val",
        "posicion": "06oro",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "7_JOYAS_REALES": {
        "fuerza": 37,
        "riqueza": 126,
        "tipo": "especial_val",
        "posicion": "07oro",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "8_JOYAS_REALES": {
        "fuerza": 38,
        "riqueza": 127,
        "tipo": "especial_val",
        "posicion": "08oro",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "9_JOYAS_REALES": {
        "fuerza": 39,
        "riqueza": 128,
        "tipo": "especial_val",
        "posicion": "09oro",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },


    "3_VINOS_VIEJOS": {
        "fuerza": 13,
        "riqueza": 81,
        "tipo": "especial_val",
        "posicion": "03cop",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "4_VINOS_VIEJOS": {
        "fuerza": 14,
        "riqueza": 82,
        "tipo": "especial_val",
        "posicion": "04cop",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "5_VINOS_VIEJOS": {
        "fuerza": 15,
        "riqueza": 83,
        "tipo": "especial_val",
        "posicion": "05cop",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "6_VINOS_VIEJOS": {
        "fuerza": 16,
        "riqueza": 84,
        "tipo": "especial_val",
        "posicion": "06cop",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "7_VINOS_VIEJOS": {
        "fuerza": 17,
        "riqueza": 85,
        "tipo": "especial_val",
        "posicion": "07cop",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "8_VINOS_VIEJOS": {
        "fuerza": 18,
        "riqueza": 86,
        "tipo": "especial_val",
        "posicion": "08cop",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "9_VINOS_VIEJOS": {
        "fuerza": 19,
        "riqueza": 87,
        "tipo": "especial_val",
        "posicion": "09cop",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    

    "2_BASTOS_PUNTIAGUDOS": {
        "fuerza": 91,
        "riqueza": 21,
        "tipo": "especial_val",
        "posicion": "02bas",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "3_BASTOS_PUNTIAGUDOS": {
        "fuerza": 92,
        "riqueza": 22,
        "tipo": "especial_val",
        "posicion": "03bas",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "4_BASTOS_PUNTIAGUDOS": {
        "fuerza": 93,
        "riqueza": 23,
        "tipo": "especial_val",
        "posicion": "04bas",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "5_BASTOS_PUNTIAGUDOS": {
        "fuerza": 94,
        "riqueza": 24,
        "tipo": "especial_val",
        "posicion": "05bas",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "6_BASTOS_PUNTIAGUDOS": {
        "fuerza": 95,
        "riqueza": 25,
        "tipo": "especial_val",
        "posicion": "06bas",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "7_BASTOS_PUNTIAGUDOS": {
        "fuerza": 96,
        "riqueza": 26,
        "tipo": "especial_val",
        "posicion": "07bas",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "8_BASTOS_PUNTIAGUDOS": {
        "fuerza": 97,
        "riqueza": 27,
        "tipo": "especial_val",
        "posicion": "08bas",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "9_BASTOS_PUNTIAGUDOS": {
        "fuerza": 98,
        "riqueza": 28,
        "tipo": "especial_val",
        "posicion": "09bas",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "10_BASTOS_PUNTIAGUDOS": {
        "fuerza": 99,
        "riqueza": 29,
        "tipo": "especial_val",
        "posicion": "10bas",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "11_BASTOS_PUNTIAGUDOS": {
        "fuerza": 100,
        "riqueza": 30,
        "tipo": "especial_val",
        "posicion": "11bas",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "12_BASTOS_PUNTIAGUDOS": {
        "fuerza": 101,
        "riqueza": 31,
        "tipo": "especial_val",
        "posicion": "12bas",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "1_BASTOS_PUNTIAGUDOS": {
        "fuerza": 102,
        "riqueza": 32,
        "tipo": "especial_val",
        "posicion": "01bas",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },


    "2_ESPADAS_ESCUDOS": {
        "fuerza": 111,
        "riqueza": 1,
        "tipo": "especial_val",
        "posicion": "02esp",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "3_ESPADAS_ESCUDOS": {
        "fuerza": 112,
        "riqueza": 2,
        "tipo": "especial_val",
        "posicion": "03esp",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "4_ESPADAS_ESCUDOS": {
        "fuerza": 113,
        "riqueza": 3,
        "tipo": "especial_val",
        "posicion": "04esp",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "5_ESPADAS_ESCUDOS": {
        "fuerza": 114,
        "riqueza": 4,
        "tipo": "especial_val",
        "posicion": "05esp",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "6_ESPADAS_ESCUDOS": {
        "fuerza": 115,
        "riqueza": 5,
        "tipo": "especial_val",
        "posicion": "06esp",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "7_ESPADAS_ESCUDOS": {
        "fuerza": 116,
        "riqueza": 6,
        "tipo": "especial_val",
        "posicion": "07esp",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "8_ESPADAS_ESCUDOS": {
        "fuerza": 117,
        "riqueza": 7,
        "tipo": "especial_val",
        "posicion": "08esp",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "9_ESPADAS_ESCUDOS": {
        "fuerza": 118,
        "riqueza": 8,
        "tipo": "especial_val",
        "posicion": "09esp",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "10_ESPADAS_ESCUDOS": {
        "fuerza": 119,
        "riqueza": 9,
        "tipo": "especial_val",
        "posicion": "10esp",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "11_ESPADAS_ESCUDOS": {
        "fuerza": 120,
        "riqueza": 10,
        "tipo": "especial_val",
        "posicion": "11esp",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "12_ESPADAS_ESCUDOS": {
        "fuerza": 121,
        "riqueza": 11,
        "tipo": "especial_val",
        "posicion": "12esp",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },
    "1_ESPADAS_ESCUDOS": {
        "fuerza": 122,
        "riqueza": 12,
        "tipo": "especial_val",
        "posicion": "01esp",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 2,
    },


    # CARTAS MÁGICAS
    "SAQUEADOR_TUMBAS": {
        "fuerza": 0,
        "riqueza": 73,
        "tipo": "especial_mag",
        "posicion": "02oro",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 3,
    },
    "CORRUPTOR": {
        "fuerza": 20,
        "riqueza": 76,
        "tipo": "especial_mag",
        "posicion": "10oro",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 3,
    },
    "MERCADER": {
        "fuerza": 50,
        "riqueza": 132,
        "tipo": "especial_mag",
        "posicion": "11oro",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 3,
    },
    "MONEDERO_PECULIAR": {
        "fuerza": 40,
        "riqueza": 131,
        "tipo": "especial_mag",
        "posicion": "01oro",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 3,
    },
    "AS_EXTRANJERO": {
        "fuerza": 41,
        "riqueza": 133,
        "tipo": "especial_mag",
        "posicion": "02cop",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 3,
    },
    "BUFON": {
        "fuerza": -1,
        "riqueza": 130,
        "tipo": "especial_mag",
        "posicion": "10cop",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 3,
    },
    "SEGADOR": {
        "fuerza": 42,
        "riqueza": 74,
        "tipo": "especial_mag",
        "posicion": "11cop",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 3,
    },
    "REBELDE": {
        "fuerza": 70,
        "riqueza": 75,
        "tipo": "especial_mag",
        "posicion": "12cop",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 3,
    },


    # CARTAS ÚNICAS
    "DON_DINERO": {
        "fuerza": 150,
        "riqueza": 150,
        "tipo": "especial_uni",
        "posicion": "12oro",
        "matadoras": ("MARTIRIZADO",),
        "recompensa": 4,
    },
    "MARTIRIZADO": {
        "fuerza": 83,
        "riqueza": 140,
        "tipo": "especial_uni",
        "posicion": "01cop",
    },
}